title: PiTag
hero_image: images/banner.png
description: Create an outdoor physical computing tag game with RFID readers
theme: red # possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2 # possible values: 1, 2 or 3
listed: false
ingredient: false
copyedit: false
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
interests: "big-project, nature/outside/weather, physical computing, games"
technologies: "electronics, physical computing, python"
site_areas:
steps:
  - title: Introduction
  - title: What you will need
  - title: Attach the header
  - title: Set up the RFID reader
