---
title: PiTag
hero_image: images/banner.png
description: Create an outdoor physical computing tag game with RFID readers
theme: red
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 2, design-0, programming-2, phys-comp-2, manufacture-2, community-0
interests: ''
technologies: electronic-components, python, raspberry-pi
site_areas: projects
hardware: electronic-components, rasperry-pi
software: python
version: 3
last_tested: 2017-01-01
steps:
- title: Introduction
- title: What you will need
- title: Attach the header
- title: Set up the RFID reader
  completion:
  - engaged
- title: Test the RFID reader
- title: Write to a card
- title: Add an LED
- title: Tag!
- title: 'Challenge: no cheating'
- title: Auto-start on boot
- title: Put it all together
  completion:
  - internal
- title: 'Challenge: more games'
